name: check

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get-latest-version
      run: |
        VERSION="$(wget 2>/dev/null https://www.irfanview.com -qSO- | grep 'Version' | sed 's|</| |' | awk '{print $2}')"
        last=$(tail -n1 .build | awk '{print $4}')

        if [ "$last" != "$VERSION" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build
        fi
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Trigger build for new version
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}